### ISSUE TITLE
invalid $show_mode error

### ISSUE THREAD

**Issue by texxasrulez** [random-cuber/contextmenu_folder#1]
I am getting this error in log folder:

hook_render_mailboxlist : invalid $show_mode:

The plugin seems to work, but I have not clicked on everything either.
Thanks for your work and plugin

**Comment by Andrei-Pozolotin** [comment]
try release 1.2.26

**Comment by texxasrulez** [comment]
Error is gone. That was a quick fix. Keep up the great work. I know it is appreciated by me. Thank you

**Comment by Andrei-Pozolotin** [comment]
thank you
