### ISSUE TITLE
Folder Actions Button not showing in Elastic 1.4.8

### ISSUE THREAD

**Issue by MetallianFR68** [random-cuber/contextmenu_folder#15]
I can't find that icon anymore with the Elastic skin.
Has this something to do with contextmenu_folder plugin ?

![image](https://user-images.githubusercontent.com/6049266/91762129-87600600-ebd5-11ea-962b-5747d362a3bf.png)

**Comment by Andrei-Pozolotin** [comment]
please submit a PR

**Comment by MetallianFR68** [comment]
Could you please merge this commit ?
This is obviously working.
Thanks
