### ISSUE TITLE
localize_foldername

### ISSUE THREAD

**Issue by donkikhot** [random-cuber/contextmenu_folder#9]
Привет, при создании папок есть проблема с названиями, после создания папка принимает вид ???
Hi, when creating folders there is a problem in the names, after creating the folder takes the form ???

**Comment by Andrei-Pozolotin** [comment]
well, I test only in locale en_US UTF-8. 

is this the same problem:?
https://github.com/random-cuber/contextmenu_folder/issues/8

**Comment by donkikhot** [comment]
No, on en_US UTF-8. there is no such problem,
is this the same problem:? # 8
not exactly the same, but I think there is a connection.

_Нет, на en_US UTF-8. такой проблемы нет, 
is this the same problem:?#8 
не совсем тоже самое, но думаю связь есть._

name folder "INBOX/testтест"
![image](https://user-images.githubusercontent.com/33314508/33542609-daf681d8-d8e4-11e7-8660-3e592e0027c9.png)

Roundcube Webmail 1.3.3
contextmenu_folder 	1.3.3
contextmenu 	2.3

` locale -a
C
C.UTF-8
en_US.utf8
POSIX
ru_RU.utf8
`
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by drlight17** [comment]
I've managed this with https://github.com/random-cuber/contextmenu_folder/pull/18

**Comment by Andrei-Pozolotin** [comment]
merged
